import type { Metadata } from 'next';
import SiteHeader from '@/components/site-header'; import SiteFooter from '@/components/site-footer'; import PageHero from '@/components/page-hero'; import Qualification from '@/components/web/qualification'; import Packages from '@/components/web/packages'; import Calculator from '@/components/web/calculator'; import FAQ from '@/components/web/faq'; import Process from '@/components/web/process'; import Guarantees from '@/components/web/guarantees'; import Cases from '@/components/web/cases'; import WebForm from '@/components/web/web-form';
import { loadDataJSON, loadJSON } from '@/lib/content'; import { buildMetadata } from '@/lib/meta'; import type { AnalyticsConfig, FormConfig } from '@/lib/data-types'; import type { CalculatorConfig, Case, FAQItem, Guarantee, PricingContent, ProcessStep } from '@/lib/web-types';

export const metadata: Metadata = buildMetadata({ title: 'Сайты и лендинги с результатом в заявках | mono', description: 'Система привлечения клиентов с измеримым результатом. Пакеты, ROI-калькулятор и прозрачный процесс.', path: '/web' });

export default function WebPage() {
  const pricing = loadJSON<PricingContent>('web/web_pricing.json'); const faq = loadJSON<FAQItem[]>('web/web_faq.json'); const guarantees = loadJSON<Guarantee[]>('web/web_guarantees.json'); const cases = loadJSON<Case[]>('web/web_cases.json'); const calculator = loadJSON<CalculatorConfig>('web/web_calculator.json'); const process = loadJSON<ProcessStep[]>('web/web_process.json'); const form = loadDataJSON<FormConfig>('form.json'); const analytics = loadDataJSON<AnalyticsConfig>('analytics.json');
  return <main><SiteHeader /><PageHero eyebrow={pricing.positioning.eyebrow} title={<>{pricing.positioning.h1[0]}<br /><span>{pricing.positioning.h1[1]}</span></>} sub={pricing.positioning.sub} anchor={pricing.anchor} cta={{ href: '#calculator', label: 'Подобрать пакет', primary: true }} secondaryCta={{ href: '#cases', label: 'Смотреть кейсы' }} /><Qualification data={pricing.qualification} /><Packages packages={pricing.packages} priceDrivers={pricing.price_drivers} /><Calculator config={calculator} analyticsEnabled={analytics.enabled} /><Process steps={process} /><Guarantees items={guarantees} /><FAQ items={faq} analyticsEnabled={analytics.enabled} /><Cases cases={cases} /><WebForm config={form} analyticsEnabled={analytics.enabled} /><SiteFooter /></main>;
}